USE DBCARRITO;

-- Drop foreign keys first (if any)
ALTER TABLE CARRITO DROP CONSTRAINT IF EXISTS FK_CARRITO_CLIENTE;
ALTER TABLE CARRITO DROP CONSTRAINT IF EXISTS FK_CARRITO_PRODUCTO;
ALTER TABLE PRODUCTO DROP CONSTRAINT IF EXISTS FK_PRODUCTO_MARCA;
ALTER TABLE PRODUCTO DROP CONSTRAINT IF EXISTS FK_PRODUCTO_CATEGORIA;
ALTER TABLE VENTA DROP CONSTRAINT IF EXISTS FK_VENTA_CLIENTE;
ALTER TABLE DETALLEVENTA DROP CONSTRAINT IF EXISTS FK_DETALLEVENTA_VENTA;
ALTER TABLE DETALLEVENTA DROP CONSTRAINT IF EXISTS FK_DETALLEVENTA_PRODUCTO;

-- Drop tables

DROP TABLE IF EXISTS USUARIO;
DROP TABLE IF EXISTS DEPARTAMENTO;
DROP TABLE IF EXISTS DETALLEVENTA;
DROP TABLE IF EXISTS VENTA;
DROP TABLE IF EXISTS CARRITO;
DROP TABLE IF EXISTS PRODUCTO;
DROP TABLE IF EXISTS MARCA;
DROP TABLE IF EXISTS CATEGORIA;
DROP TABLE IF EXISTS CLIENTE;

CREATE TABLE CATEGORIA (
    IdCategoria INT PRIMARY KEY IDENTITY,
    Descripcion VARCHAR(100),
    Activo BIT DEFAULT 1,
    FechaRegistro DATETIME DEFAULT GETDATE()
);
GO

CREATE TABLE MARCA (
    IdMarca INT PRIMARY KEY IDENTITY,
    Descripcion VARCHAR(100),
    Activo BIT DEFAULT 1,
    FechaRegistro DATETIME DEFAULT GETDATE()
);

GO

CREATE TABLE PRODUCTO (
    IdProducto INT PRIMARY KEY IDENTITY,
    Nombre VARCHAR(500),
    Descripcion VARCHAR(500),
    IdMarca INT,
    IdCategoria INT,
    Precio DECIMAL(10, 2) DEFAULT 0,
    Stock INT,
    RutaImagen VARCHAR(100),
    NombreImagen VARCHAR(100),
    Activo BIT DEFAULT 1,
    FechaRegistro DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (IdMarca) REFERENCES MARCA(IdMarca),
    FOREIGN KEY (IdCategoria) REFERENCES CATEGORIA(IdCategoria)
);

GO

CREATE TABLE CLIENTE (
    IdCliente INT PRIMARY KEY IDENTITY,
    Nombre VARCHAR(100),
    Correo VARCHAR(100),
    Clave VARCHAR(200),
    Reestablecer BIT DEFAULT 0,
    FechaRegistro DATETIME DEFAULT GETDATE()
);

GO

CREATE TABLE CARRITO (
    IdCarrito INT PRIMARY KEY IDENTITY,
    IdCliente INT,
    IdProducto INT,
    Cantidad INT,
    FOREIGN KEY (IdCliente) REFERENCES CLIENTE(IdCliente),
    FOREIGN KEY (IdProducto) REFERENCES PRODUCTO(IdProducto)
);

GO

CREATE TABLE VENTA (
    IdVenta INT PRIMARY KEY IDENTITY,
    IdCliente INT REFERENCES CLIENTE(IdCliente),
    TotalProducto INT,
    MontoTotal DECIMAL(10, 2),
    Contacto VARCHAR(100),
    IdDepartamento VARCHAR(100),
    Telefono VARCHAR(50),
    IdTransaccion VARCHAR(100),
    FechaVenta DATETIME DEFAULT GETDATE()
);

GO

CREATE TABLE DETALLEVENTA (
    IdDetalleVenta INT PRIMARY KEY IDENTITY,
    IdVenta INT REFERENCES VENTA(IdVenta),
    IdProducto INT REFERENCES PRODUCTO(IdProducto),
    Cantidad INT,
    Total DECIMAL(10, 2)
);

CREATE TABLE USUARIO(
	IdUsuario INT PRIMARY KEY IDENTITY,
	Nombre VARCHAR (100),
	Apellido VARCHAR(100),
	Correo VARCHAR(100),
	Clave VARCHAR(500),
	Reestablecer BIT DEFAULT 1,
	Activo BIT DEFAULT 1,
	FechaRegistro DATETIME DEFAULT GETDATE()
);

GO

CREATE TABLE DEPARTAMENTO(
	IdDepartamento VARCHAR(2) NOT NULL,
	Descripcion VARCHAR(45) NOT NULL,
);

GO

